# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:0.68.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo 
  except:
    - pages

pages:
  script:
    - hugo 

  artifacts:
    paths:
      - public
  only:
    - pages

