# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo --config=site/config.toml --themesDir=site/themes --contentDir=site/content -d site -s site/

  except:
    - dev 
pages:
  script:
    - hugo --config=site/config.toml --themesDir=site/themes --contentDir=site/content -d site/public -s site/

  artifacts:
    paths:
      - public
  only:
    - dev 
