baseURL = "https://jhilker.gitlab.io/pyronsworn"
languageCode = "en-us"
title = "Pyronsworn"
theme = "book"

## Book Params Theme
[params]
BookSection = "*"
BookCollapseSection = true
BookTheme = "dark"