site_name: Chronicler for CK3
repo_url: https://gitlab.com/jhilker/pyronsworn/
repo_name: jhilker/pyronsworn
edit_uri: /-/edit/dev/docs/
nav:
  - Home: index.md
  - Install: install.md
theme: 
  name: "material"
  palette: 
    scheme: slate
    primary: light blue
    accent: amber
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    custom_templates: templates
    watch:
      - pyronsworn
